[package]
name = "poorly_written_program"
version = "0.1.0"
edition = "2021"
authors = [ "MaybeAnonymous" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23"
colored = "2"
